#!/usr/bin/env python
# Neon Touge native extension. Examples:
#   scons platform=android arch=arm64 target=template_release
#   scons platform=windows use_mingw=yes use_llvm=yes mingw_prefix=D:/RP4Toolchain/llvm-mingw target=template_debug
import os

env = SConscript("../thirdparty/godot-cpp/SConstruct", {"api_version": "4.7"})

env.Append(CPPPATH=["src/"])
sources = Glob("src/sim/*.cpp") + Glob("src/sim/world/*.cpp") + Glob("src/gd/*.cpp")

if env["platform"] == "android":
    # Dimensity 1100: Cortex-A78 + A55 are ARMv8.2-A with dotprod/fp16.
    env.Append(CCFLAGS=["-march=armv8.2-a+fp16+dotprod", "-O3", "-fno-math-errno"])
elif env["platform"] == "windows":
    env.Append(CCFLAGS=["-O2"])

out_dir = "../godot/native/bin/"
library = env.SharedLibrary(
    out_dir + "libneontouge{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
env.NoCache(library)
Default(library)
