class_name WorldStreamer
extends Node3D
## Streams 256 m chunks around a focus point in LOD rings. Chunk geometry is generated by
## NTWorld on WorkerThreadPool threads; the main thread only uploads finished chunks (one per
## frame within a time budget) and feeds collision for the nearest chunks into NTSim.

signal chunk_loaded(cx: int, cz: int, lod: int)
signal initial_load_done

const COLLISION_ID_BASE := 10_000_000

var world: NTWorld
var sim: NTSim
var focus := Vector3.ZERO
var focus_velocity := Vector3.ZERO
## Chebyshev ring radius (in chunks) per LOD level; everything beyond the last ring is unloaded.
var rings := [1, 2, 4, 7]
var collision_radius := 1
var max_jobs := 3
var upload_budget_ms := 4.0

var _chunks := {} # Vector2i -> {"lod": int, "node": Node3D, "collision": bool, "lights": PackedFloat32Array}
var _pending := {} # Vector2i -> {"lod": int, "collision": bool}
var _jobs := {} # task id -> Vector2i
var _results := [] # finished chunk dictionaries
var _mutex := Mutex.new()
var _timer := 0.0
var _initial_left := -1

func setup(p_world: NTWorld, p_sim: NTSim) -> void:
	world = p_world
	sim = p_sim
	var tier: int = Settings.get_value("graphics", "tier", Settings.Tier.HIGH)
	var dd: float = Settings.get_value("graphics", "draw_distance", 1.0)
	match tier:
		Settings.Tier.LOW: rings = [1, 2, 3, 5]
		Settings.Tier.MEDIUM: rings = [1, 2, 3, 6]
		Settings.Tier.ULTRA: rings = [1, 3, 5, 9]
		_: rings = [1, 2, 4, 7]
	rings[3] = int(round(rings[3] * dd))

## Blocks nothing: call, then wait for `initial_load_done` before releasing the player.
func prime(position: Vector3) -> void:
	focus = position
	_update_requests()
	_initial_left = _pending.size()

func desired_lod(c: Vector2i, center: Vector2i) -> int:
	var d := maxi(absi(c.x - center.x), absi(c.y - center.y))
	for i in range(rings.size()):
		if d <= rings[i]:
			return i
	return -1

func lights_near(pos: Vector3, radius: float) -> PackedFloat32Array:
	var out := PackedFloat32Array()
	var r2 := radius * radius
	for key in _chunks.keys():
		var ch: Dictionary = _chunks[key]
		if ch.lod > 1:
			continue
		var l: PackedFloat32Array = ch.lights
		for i in range(0, l.size(), 5):
			var dx := l[i] - pos.x
			var dz := l[i + 2] - pos.z
			if dx * dx + dz * dz < r2:
				out.append_array(l.slice(i, i + 5))
	return out

func _process(delta: float) -> void:
	if world == null or not world.is_built():
		return
	_timer -= delta
	if _timer <= 0.0:
		_timer = 0.2
		_update_requests()
	_dispatch_jobs()
	_upload_results()

func _update_requests() -> void:
	var lookahead := focus + focus_velocity * 2.5
	var center := world.chunk_of(lookahead)
	var here := world.chunk_of(focus)
	var max_r: int = rings[rings.size() - 1]
	var wanted := {}
	for dz in range(-max_r, max_r + 1):
		for dx in range(-max_r, max_r + 1):
			var c := Vector2i(center.x + dx, center.y + dz)
			if c.x < 0 or c.y < 0 or c.x >= world.chunks_x() or c.y >= world.chunks_z():
				continue
			var lod := desired_lod(c, center)
			if lod < 0:
				continue
			var col := maxi(absi(c.x - here.x), absi(c.y - here.y)) <= collision_radius or maxi(absi(c.x - center.x), absi(c.y - center.y)) <= collision_radius
			if col:
				lod = 0
			wanted[c] = {"lod": lod, "collision": col}
	# Unload chunks no longer wanted.
	for key in _chunks.keys():
		if not wanted.has(key):
			_unload(key)
	# Queue (re)builds where the LOD or collision need changed.
	for key in wanted.keys():
		var w: Dictionary = wanted[key]
		var have: Dictionary = _chunks.get(key, {})
		var pend: Dictionary = _pending.get(key, {})
		var ok: bool = not have.is_empty() and have.lod == w.lod and (have.collision or not w.collision)
		if ok:
			continue
		if not pend.is_empty() and pend.lod == w.lod and pend.collision == w.collision:
			continue
		_pending[key] = w

func _dispatch_jobs() -> void:
	if _pending.is_empty() or _jobs.size() >= max_jobs:
		return
	var center := world.chunk_of(focus + focus_velocity * 2.5)
	var keys := _pending.keys()
	keys.sort_custom(func(a, b): return (a - center).length_squared() < (b - center).length_squared())
	for key in keys:
		if _jobs.size() >= max_jobs:
			break
		var already := false
		for k in _jobs.values():
			if k == key:
				already = true
		if already:
			continue
		var req: Dictionary = _pending[key]
		_pending.erase(key)
		var lod: int = req.lod
		var props := lod <= 2
		var density: float = [1.0, 0.7, 0.35, 0.0][lod] * float(Settings.get_value("graphics", "foliage", 1.0))
		var task := WorkerThreadPool.add_task(_build_job.bind(key, lod, req.collision, props, density), false, "chunk %s" % key)
		_jobs[task] = key

func _build_job(key: Vector2i, lod: int, collision: bool, props: bool, density: float) -> void:
	var d := world.build_chunk(key.x, key.y, lod, collision, props, density)
	# Mesh creation from packed arrays is thread-safe; do it here to keep the main thread light.
	d["mesh"] = NTWorld.make_mesh(d)
	_mutex.lock()
	_results.append(d)
	_mutex.unlock()

func _upload_results() -> void:
	# Retire finished tasks.
	for task in _jobs.keys():
		if WorkerThreadPool.is_task_completed(task):
			WorkerThreadPool.wait_for_task_completion(task)
			_jobs.erase(task)
	var t0 := Time.get_ticks_usec()
	while true:
		_mutex.lock()
		var d: Dictionary = _results.pop_front() if not _results.is_empty() else {}
		_mutex.unlock()
		if d.is_empty():
			break
		_integrate(d)
		if (Time.get_ticks_usec() - t0) / 1000.0 > upload_budget_ms:
			break

func _integrate(d: Dictionary) -> void:
	var key := Vector2i(d.cx, d.cz)
	var node := Node3D.new()
	node.name = "Chunk_%d_%d_L%d" % [key.x, key.y, d.lod]
	var mesh: ArrayMesh = d.mesh
	if mesh.get_surface_count() > 0:
		var mi := MeshInstance3D.new()
		mi.mesh = mesh
		var groups: PackedInt32Array = mesh.get_meta("surface_groups")
		for s in range(groups.size()):
			mi.set_surface_override_material(s, WorldMaterials.get_material(groups[s]))
		# Far LODs don't need to cast shadows (they're beyond the shadow distance anyway).
		if d.lod >= 2:
			mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		node.add_child(mi)
	var props: Dictionary = d.get("props", {})
	for t in props.keys():
		node.add_child(PropLibrary.multimesh_instance(int(t), props[t]))
	add_child(node)
	var had: Dictionary = _chunks.get(key, {})
	if not had.is_empty():
		had.node.queue_free()
	var col := d.has("collision_faces")
	if col and sim:
		sim.set_collision_chunk(COLLISION_ID_BASE + key.x * 1000 + key.y, d.collision_faces, d.collision_surfaces, d.collision_flags)
	elif not had.is_empty() and had.collision and sim:
		sim.remove_collision_chunk(COLLISION_ID_BASE + key.x * 1000 + key.y)
	_chunks[key] = {"lod": d.lod, "node": node, "collision": col, "lights": d.lights}
	chunk_loaded.emit(key.x, key.y, d.lod)
	if _initial_left > 0:
		_initial_left -= 1
		if _initial_left == 0:
			initial_load_done.emit()

func _unload(key: Vector2i) -> void:
	var ch: Dictionary = _chunks[key]
	ch.node.queue_free()
	if ch.collision and sim:
		sim.remove_collision_chunk(COLLISION_ID_BASE + key.x * 1000 + key.y)
	_chunks.erase(key)

## True once physics collision covers the chunk at `pos` and its 8 neighbours.
func has_collision_at(pos: Vector3) -> bool:
	var c := world.chunk_of(pos)
	for dz in range(-1, 2):
		for dx in range(-1, 2):
			var key := Vector2i(c.x + dx, c.y + dz)
			if key.x < 0 or key.y < 0 or key.x >= world.chunks_x() or key.y >= world.chunks_z():
				continue
			var ch: Dictionary = _chunks.get(key, {})
			if ch.is_empty() or not ch.collision:
				return false
	return true

func loaded_count() -> int:
	return _chunks.size()

func pending_count() -> int:
	return _pending.size() + _jobs.size()
